### ISSUE TITLE
Implementing Stack and Queue program in C

### ISSUE THREAD

**Issue by aparnamittal** [PeanutCoffee/DSA#237]

**Comment by aparnamittal** [comment]
@PeanutCoffee pls assign me this issue under hacktoberfest

**Comment by Prajwal-2002** [comment]
@PeanutCoffee please assign this issue to me

**Comment by PeanutCoffee** [comment]
This repo has been excluded from hacktoberfest 2022.

**Comment by aparnamittal** [comment]
@PeanutCoffee what issues can be added to contribute in hacktoberfest
