### ISSUE TITLE
Created Bubble Sort algorithm in Python3

### ISSUE THREAD

**Issue by varshilshah-2002** [PeanutCoffee/DSA#33]
Bubble sort algorithm in Python3.

**Comment by PeanutCoffee** [comment]
Upload the corresponding code.

**Comment by varshilshah-2002** [comment]
Code for Bubble Sort Algorithm
`def bubbleSort(arr):
     
    n = len(arr)
 
    # For loop to traverse through all
    # element in an array
    for i in range(n):
        for j in range(0, n - i - 1):
             
            # Range of the array is from 0 to n-i-1
            # Swap the elements if the element found
            #is greater than the adjacent element
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                 
# Driver code
 
# Example to test the above code
arr = [ 2, 1, 10, 23 ]
 
bubbleSort(arr)
 
print("Sorted array is:")
for i in range(len(arr)):
    print("%d" % arr[i])`

**Comment by PeanutCoffee** [comment]
Fork the repo, then add the code in the python folder. Then create a pull request with the same title as the issue title.
